// Pure commit-hygiene guard logic. No git access — operates on already-extracted
// commit message strings so it is fully unit-testable.
// See .claude/handshakes/feat-agents-contribution-ruleset.md §4.B (Guard 2).
//
// A single commit message FAILS on any of:
//   1. a `Co-authored-by:` trailer (any value, case-insensitive, line start).
//   2. a "Generated with"/"Generated by" footer (case-insensitive).
//   3. a subject line missing a Conventional Commit prefix.
//   4. no issue reference (no `#<digits>` anywhere in the message).
//
// Merge commits (subject starts with "Merge ") are exempt — they are generated
// by git, not authored. Revert commits are permitted via the `revert` prefix.

const CONVENTIONAL_TYPES = [
  "feat",
  "fix",
  "docs",
  "chore",
  "refactor",
  "test",
  "build",
  "ci",
  "perf",
  "style",
  "revert",
];

// type, optional (scope), optional !, then ": "
const CONVENTIONAL_RE = new RegExp(
  `^(${CONVENTIONAL_TYPES.join("|")})(\\([^)]+\\))?!?: .+`,
);

const COAUTHOR_RE = /^co-authored-by:/im;
const GENERATED_RE = /generated\s+(with|by)\b/i;
const ISSUE_REF_RE = /#\d+/;

/**
 * @param {string} message  full commit message (subject + body)
 * @returns {{ ok: boolean, violations: string[], skipped?: boolean }}
 */
export function lintCommitMessage(message) {
  const msg = String(message ?? "");
  const subject = msg.split("\n", 1)[0].trim();

  // Merge commits are git-generated; exempt them entirely.
  if (/^Merge /.test(subject)) {
    return { ok: true, violations: [], skipped: true };
  }

  const violations = [];

  if (COAUTHOR_RE.test(msg)) {
    violations.push("contains a Co-authored-by trailer (not allowed)");
  }

  if (GENERATED_RE.test(msg)) {
    violations.push('contains a "Generated with/by" footer (not allowed)');
  }

  if (!CONVENTIONAL_RE.test(subject)) {
    violations.push(
      `subject "${subject}" lacks a Conventional Commit prefix (${CONVENTIONAL_TYPES.join("|")})(scope)?!?: `,
    );
  }

  if (!ISSUE_REF_RE.test(msg)) {
    violations.push("does not reference an issue (#<number>)");
  }

  return { ok: violations.length === 0, violations };
}

/**
 * Lint an array of commit messages (e.g. from `git log --format=%B%x00`).
 * @param {string[]} messages
 * @returns {{ ok: boolean, violations: string[] }}
 */
export function lintRange(messages) {
  const all = [];
  for (const message of messages) {
    const subject = String(message ?? "").split("\n", 1)[0].trim();
    const { violations } = lintCommitMessage(message);
    for (const v of violations) {
      all.push(`[${subject || "<empty subject>"}] ${v}`);
    }
  }
  return { ok: all.length === 0, violations: all };
}
